# Generated by Django 3.1.4 on 2020-12-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
