# Generated by Django 3.1.4 on 2020-12-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0003_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
